# Generated by Django 4.1.6 on 2023-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withinapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madelname', models.CharField(max_length=100, verbose_name='Model name')),
                ('makeyear', models.CharField(max_length=4, verbose_name='Make year')),
            ],
        ),
    ]
